# CALIDAD DE DATOS

**IMPORTANTE**: Recuerda hacer una copia de esta plantilla para no machacar la original.

## IMPORTAR PAQUETES

In [37]:
import numpy as np
import pandas as pd
from janitor import clean_names

#Automcompletar rápido
%config IPCompleter.greedy=True

## IMPORTAR LOS DATOS

Sustituir la ruta del proyecto.

In [38]:
ruta_proyecto = 'C:/Users/sergi/Desktop/DATA/CURSO DS4B/EstructuraDirectorio/03_MACHINE_LEARNING/08_CASOS/01_LEADSCORING'

Sustituir el nombre_fichero_datos.

In [39]:
nombre_fichero_datos = 'trabajo.csv'

Cargar los datos.

In [40]:
ruta_completa = ruta_proyecto + '/02_Datos/03_Trabajo/' + nombre_fichero_datos

df = pd.read_csv(ruta_completa,index_col='id', sep = ',')
df

,origen,fuente,no_enviar_email,no_llamar,compra,visitas_total,tiempo_en_site_total,paginas_vistas_visita,ult_actividad,ambito,ocupacion,conociste_google,conociste_revista,conociste_periodico,conociste_youtube,conociste_facebook,conociste_referencias,score_actividad,score_perfil,descarga_lm
id,,,,,,,,,,,,,,,,,,,,
660737,API,Chat,No,No,0,0.0,0,0.00,Page Visited on Website,Select,Unemployed,No,No,No,No,No,No,15.0,15.0,No
660728,API,Organic Search,No,No,0,5.0,674,2.50,Email Opened,Select,Unemployed,No,No,No,No,No,No,15.0,15.0,No
660680,API,Chat,No,No,0,0.0,0,0.00,Chat Conversation,NaN,NaN,No,No,No,No,No,No,17.0,15.0,No
660673,Landing Page Submission,Google,No,No,1,2.0,1640,2.00,Email Opened,Supply Chain Management,Unemployed,No,No,No,No,No,No,14.0,20.0,No
660664,API,Chat,No,No,0,0.0,0,0.00,Chat Conversation,NaN,NaN,No,No,No,No,No,No,15.0,15.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
579615,Landing Page Submission,Direct Traffic,No,No,1,5.0,210,2.50,SMS Sent,Business Administration,Unemployed,No,No,No,No,No,No,14.0,20.0,No
579564,Landing Page Submission,Direct Traffic,Yes,No,1,8.0,1845,2.67,Email Marked Spam,IT Projects Management,Unemployed,No,No,No,No,No,No,15.0,17.0,No
579546,Landing Page Submission,Direct Traffic,No,No,0,2.0,238,2.00,SMS Sent,Media and Advertising,Unemployed,No,No,No,No,No,No,14.0,19.0,Yes
579545,Landing Page Submission,Direct Traffic,Yes,No,0,2.0,199,2.00,SMS Sent,Business Administration,Unemployed,No,No,No,No,No,No,13.0,20.0,Yes
579533,Landing Page Submission,Direct Traffic,No,No,1,6.0,1279,3.00,SMS Sent,Supply Chain Management,Unemployed,No,No,No,No,No,No,15.0,18.0,Yes

## CORRECCIÓN DE NOMBRES DE VARIABLES

## VISIÓN GENERAL

In [41]:
df.head()

,origen,fuente,no_enviar_email,no_llamar,compra,visitas_total,tiempo_en_site_total,paginas_vistas_visita,ult_actividad,ambito,ocupacion,conociste_google,conociste_revista,conociste_periodico,conociste_youtube,conociste_facebook,conociste_referencias,score_actividad,score_perfil,descarga_lm
id,,,,,,,,,,,,,,,,,,,,
660737,API,Chat,No,No,0,0.0,0,0.0,Page Visited on Website,Select,Unemployed,No,No,No,No,No,No,15.0,15.0,No
660728,API,Organic Search,No,No,0,5.0,674,2.5,Email Opened,Select,Unemployed,No,No,No,No,No,No,15.0,15.0,No
660680,API,Chat,No,No,0,0.0,0,0.0,Chat Conversation,NaN,NaN,No,No,No,No,No,No,17.0,15.0,No
660673,Landing Page Submission,Google,No,No,1,2.0,1640,2.0,Email Opened,Supply Chain Management,Unemployed,No,No,No,No,No,No,14.0,20.0,No
660664,API,Chat,No,No,0,0.0,0,0.0,Chat Conversation,NaN,NaN,No,No,No,No,No,No,15.0,15.0,No

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6365 entries, 660737 to 579533
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   origen                 6365 non-null   object
 1   fuente                 6342 non-null   object
 2   no_enviar_email        6365 non-null   object
 3   no_llamar              6365 non-null   object
 4   compra                 6365 non-null   int64
 5   visitas_total          6278 non-null   float64
 6   tiempo_en_site_total   6365 non-null   int64
 7   paginas_vistas_visita  6278 non-null   float64
 8   ult_actividad          6300 non-null   object
 9   ambito                 5343 non-null   object
 10  ocupacion              4467 non-null   object
 11  conociste_google       6365 non-null   object
 12  conociste_revista      6365 non-null   object
 13  conociste_periodico    6365 non-null   object
 14  conociste_youtube      6365 non-null   object
 15  conociste_facebook     6365 non-null   object
 16  conociste_referencias  6365 non-null   object
 17  score_actividad        3467 non-null   float64
 18  score_perfil           3467 non-null   float64
 19  descarga_lm            6365 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 1.0+ MB

## TIPOS DE DATOS

### Identificación

In [43]:
df.dtypes

origen                    object
fuente                    object
no_enviar_email           object
no_llamar                 object
compra                     int64
visitas_total            float64
tiempo_en_site_total       int64
paginas_vistas_visita    float64
ult_actividad             object
ambito                    object
ocupacion                 object
conociste_google          object
conociste_revista         object
conociste_periodico       object
conociste_youtube         object
conociste_facebook        object
conociste_referencias     object
score_actividad          float64
score_perfil             float64
descarga_lm               object
dtype: object

### Corrección

In [44]:
df = df.astype({'visitas_total':'Int64'})

df.dtypes

origen                    object
fuente                    object
no_enviar_email           object
no_llamar                 object
compra                     int64
visitas_total              Int64
tiempo_en_site_total       int64
paginas_vistas_visita    float64
ult_actividad             object
ambito                    object
ocupacion                 object
conociste_google          object
conociste_revista         object
conociste_periodico       object
conociste_youtube         object
conociste_facebook        object
conociste_referencias     object
score_actividad          float64
score_perfil             float64
descarga_lm               object
dtype: object

## VALORES ÚNICOS

### Identificación

In [45]:
df.nunique().sort_values()

conociste_youtube           1
conociste_revista           1
descarga_lm                 2
conociste_referencias       2
no_enviar_email             2
no_llamar                   2
compra                      2
conociste_facebook          2
conociste_periodico         2
conociste_google            2
origen                      4
ocupacion                   6
score_perfil               10
score_actividad            12
fuente                     16
ult_actividad              17
ambito                     19
visitas_total              38
paginas_vistas_visita      97
tiempo_en_site_total     1578
dtype: int64

### Corrección

In [46]:
df.drop(columns = ['conociste_youtube','conociste_revista'], inplace = True)

## DUPLICADOS

### Identificación

In [47]:
df.duplicated().sum()

1094

### Corrección

In [48]:
df.drop_duplicates(inplace = True)

## SEPARAR NUMÉRICAS Y CATEGÓRICAS

### Categóricas

In [49]:
cat = df.select_dtypes(exclude = 'number').copy()

### Numéricas

In [50]:
num = df.select_dtypes(include='number').copy()

## GESTIÓN DE CATEGÓRICAS

### Nulos

#### Identificación

In [51]:
cat.isna().sum().sort_values(ascending = False)

ocupacion                1359
ambito                    483
ult_actividad              65
fuente                     14
origen                      0
no_enviar_email             0
no_llamar                   0
conociste_google            0
conociste_periodico         0
conociste_facebook          0
conociste_referencias       0
descarga_lm                 0
dtype: int64

#### Corrección

In [52]:
cat.ocupacion.value_counts()

ocupacion
Unemployed              3318
Working Professional     437
Student                  131
Other                     13
Housewife                  7
Businessman                6
Name: count, dtype: int64

##### Imputar por un valor

###### Variables a imputar

In [53]:
var_imputar_valor = ['origen',
                     'fuente',
                     'no_enviar_email',
                     'no_llamar',
                     'ult_actividad',
                     'conociste_google',
                     'conociste_periodico',
                     'conociste_facebook',
                     'conociste_referencias',
                     'descarga_lm']

###### Valor por el que imputar

In [54]:
valor = 'DESCONOCIDO'

###### Imputar

In [55]:
cat[var_imputar_valor] = cat[var_imputar_valor].fillna(valor)

##### Imputar por la moda

###### Variables a imputar

In [56]:
var_imputar_moda = ['ocupacion','ambito']

###### Funcion para imputar con la moda

In [57]:
def imputar_moda(variable):
    return(variable.fillna(variable.mode()[0]))

###### Imputar con la moda

In [58]:
cat[var_imputar_moda] = cat[var_imputar_moda].apply(imputar_moda)

### Atípicos

#### Categorías poco frecuentes

##### Función para agrupar categorías raras en 'OTROS'

In [59]:
def agrupar_cat_raras(variable, criterio = 0.02):
    #Calcula las frecuencias
    frecuencias = variable.value_counts(normalize=True)
    #Identifica las que están por debajo del criterio
    temp = [cada for cada in frecuencias.loc[frecuencias < criterio].index.values]
    #Las recodifica en 'OTROS'
    temp2 = np.where(variable.isin(temp),'OTROS',variable)
    #Devuelve el resultado
    return(temp2)

##### Variables a imputar

In [60]:
var_imputar_moda = cat.columns.to_list()

##### Aplicar

In [61]:
for variable in var_imputar_moda:
    cat[variable] = agrupar_cat_raras(cat[variable],criterio = 0.02)

## GESTIÓN DE NUMÉRICAS

### Nulos

#### Identificación

In [66]:
num.isna().sum().sort_values(ascending = False)

compra                   0
visitas_total            0
tiempo_en_site_total     0
paginas_vistas_visita    0
score_actividad          0
score_perfil             0
dtype: int64

#### Corrección

##### Imputar por la mediana

###### Variables a imputar

In [63]:
var_imputar_mediana = num.columns.to_list()

###### Funcion para imputar con la mediana

In [64]:
def imputar_mediana(variable):
    if pd.api.types.is_integer_dtype(variable):
        return(variable.fillna(int(variable.median())))
    else:
        return(variable.fillna(variable.median()))

###### Imputar con la mediana

In [65]:
num[var_imputar_mediana] = num[var_imputar_mediana].apply(imputar_mediana)

### Atípicos

#### Por desviación típica

##### Identificación

###### Definir el número de desviaciones típicas

In [67]:
num_desv_tip = 4

###### Función que devuelve los índices de los atípicos

In [68]:
def atipicos_desv_tip(variable, num_desv_tip = 4):
    #sacamos los nulos por ahora
    variable = variable.dropna()
    #calculamos los límites
    media = np.mean(variable)
    sd = np.std(variable)
    umbral = sd * num_desv_tip
    lim_inf = media - umbral
    lim_sup = media + umbral
    #encontramos los índices de los que están fuera de los límites
    indices = [indice for indice,valor in variable.items() if valor < lim_inf or valor > lim_sup]
    return(indices)

###### Función que cuenta el número de atípicos

In [69]:
def conteo_atipicos(df,variable, num_desv_tip = 4):
    atipicos = atipicos_desv_tip(df[variable], num_desv_tip)
    return(df.loc[atipicos,variable].value_counts())

###### Variables a aplicar

In [70]:
var_atipicos_dt = num.columns.to_list()

###### Aplicar

In [71]:
for variable in var_atipicos_dt:
    print('\n' + variable + ':\n')
    print(conteo_atipicos(num,variable,num_desv_tip))

compra:

Series([], Name: count, dtype: int64)

visitas_total:

visitas_total
27     4
29     2
26     2
43     1
30     1
55     1
74     1
41     1
54     1
115    1
251    1
32     1
Name: count, dtype: Int64

tiempo_en_site_total:

Series([], Name: count, dtype: int64)

paginas_vistas_visita:

paginas_vistas_visita
14.00    7
12.00    4
13.00    4
15.00    3
16.00    2
55.00    1
12.33    1
24.00    1
14.50    1
11.50    1
Name: count, dtype: int64

score_actividad:

score_actividad
10.0    39
9.0      6
8.0      4
18.0     3
7.0      1
Name: count, dtype: int64

score_perfil:

Series([], Name: count, dtype: int64)

##### Corrección

#### Por winsorización manual para una variable

##### Corrección

###### Aplicar

In [75]:
num['visitas_total'] = num['visitas_total'].clip(0, 50)
num['paginas_vistas_visita'] = num['paginas_vistas_visita'].clip(0, 20)

## GUARDAR DATASETS TRAS CALIDAD DE DATOS

Guarda los avances en df, cat y num con un sufijo para poder guardar o recuperar avances del proyecto.

En formato pickle para no perder las modificaciones de metadatos.

### Definir los nombres de los archivos

In [76]:
ruta_trabajo = ruta_proyecto + '/02_Datos/03_Trabajo/' + 'trabajo_resultado_calidad.pickle'
ruta_cat = ruta_proyecto + '/02_Datos/03_Trabajo/' + 'cat_resultado_calidad.pickle'
ruta_num = ruta_proyecto + '/02_Datos/03_Trabajo/' + 'num_resultado_calidad.pickle'

### Guardar los archivos

In [77]:
df.to_pickle(ruta_trabajo)
cat.to_pickle(ruta_cat)
num.to_pickle(ruta_num)